### PR TITLE
fixed missing headers with post gcc 4.7

### PR DESCRIPTION
**Pull request by alinelena**

### CODE REVIEW

**Comment by foolab** [comment]
Why are those needed?

**Comment by alinelena** [comment]
to be able to build them when using gcc 4.7 or above compilers since 
unistd is not included anymore down the chain. 
The same for camera.
Regards, 
Alin
On Sat, Jul 25, 2015 at 04:44:59pm -0700, Mohammed Sameer wrote:

> Why are those needed?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/foolab/quill/pull/1#issuecomment-124916181

## 

Without Questions there are no Answers!

---

Dr. Alin Marin ELENA
http://alin.elena.space/

---

**Comment by foolab** [comment]
which functions need them?

**Comment by alinelena** [comment]
mutex and getppid and usleep for cameraplus

On Sun, Jul 26, 2015 at 05:23:13am -0700, Mohammed Sameer wrote:

> which functions need them?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/foolab/quill/pull/1#issuecomment-124976546

## 

Without Questions there are no Answers!

---

Dr. Alin Marin ELENA
http://alin.elena.space/

---

**Pull request merged**
